language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libmpdclient-dev
    - sudo apt-get install -y lua-filesystem
    - sudo apt-get install -y lua5.3
    - sudo apt-get install -y liblua5.3-dev
    - sudo apt-get install -y libxmmsclient-dev
    - sudo apt-get install -y libxmmsclient-glib-dev
    - sudo apt-get install -y xmms2
script:
    make all && make install
