language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libmpdclient2
    - sudo apt-get install -y lua5.2
    - sudo apt-get install -y luafilesystem
    - sudo apt-get install -y xmms2
script:
    make all && make install
