language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libmpdclient-dev
    - sudo apt-get install -y lua5.1
    - sudo apt-get install -y liblua5.1-filesystem0
    - sudo apt-get install -y xmms2
script:
    make all && make install
